TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 0.82
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  holonomic_robot: true
  meter_scoring: true
  # dwa: true
